### ISSUE TITLE
No static method toUnsignedInt(B)I in class Ljava/lang/Byte; or its super classes (declaration of 'java.lang.Byte' appears in /system/framework/core-oj.jar)

### ISSUE THREAD

**Issue by rohanagarwal94** [codahale/shamir#10]
@codahale This is the error on the execution of the line 

> final Map<Integer, byte[]> parts = scheme.split(secret);

**Comment by codahale** [comment]
This library requires Java 8 or newer.

**Comment by rohanagarwal94** [comment]
@codahale is it possible in any way to run in Java 7? Android does not provide full Java language support as of yet.

**Comment by codahale** [comment]
I’ve never done any Android programming, so I don’t have any advice for you. Java 7’s last update was more than three years ago. All the code I write is for Java 8. Once Java 11 is released, I’ll begin to target that.
