### ISSUE TITLE
g^510 and g^511

### ISSUE THREAD

**Issue by fcorneli** [codahale/shamir#12]
When I calculate g^510 and g^511 manually, I get values 1 and 3. Why does the `EXP` table contain values 0 and 0 here?
https://github.com/codahale/shamir/blob/58b9502bc96f8749a64d9ff81b5c35f0b0dde354/src/main/java/com/codahale/shamir/GF256.java#L146

**Comment by codahale** [comment]
Those are never actually referenced, since `EXP` only extends to `255+255`.

This table was generated using the procedure specified here: https://github.com/rsc/qr/blob/master/gf256/gf256.go#L21

**Comment by fcorneli** [comment]
Sure that g^510 is not required for 255+255?

**Comment by codahale** [comment]
https://github.com/codahale/shamir/blob/master/src/main/java/com/codahale/shamir/GF256.java#L158-L160

**Comment by fcorneli** [comment]
Put g^510 and g^511 there and you can kick out an `if`in `mul`... no?

**Comment by codahale** [comment]
You’re missing the point — it’s a lookup table for the results of everything except `a=0` or `b=0`, so it only needs to be 510 elements long. Please stop opening issues unless you can write a test demonstrating a problem with the code.
