### ISSUE TITLE
use case: given points

### ISSUE THREAD

**Issue by fcorneli** [codahale/shamir#13]
I have this use case where I want to construct a polynomial where I have as input the secret and some additional predefined points. The idea is that each "application" (whatever that is) can present its own point(s), and that the secret remains the same, independent of the "application". Hence you can have a single AES encryption (key) shared by all "applications".

**Comment by codahale** [comment]
I can’t help you with that.

**Comment by fcorneli** [comment]
FYI... implemented this feature. Available at: https://github.com/e-Contract/shamir/tree/fcorneli

**Comment by fcorneli** [comment]
PR available at https://github.com/codahale/shamir/pull/14
