### ISSUE TITLE
Gradle build?

### ISSUE THREAD

**Issue by rohanagarwal94** [codahale/shamir#8]
Hello @codahale ,
I would appreciate if you could provide a gradle build for the library. You could use jitpack.io

**Comment by rohanagarwal94** [comment]
Found it.

**Comment by rohanagarwal94** [comment]
Found the library from jitpack, but not working as expected. Is a gradle build possible?

**Comment by codahale** [comment]
Hi Rohan,

This project is built with Maven and will continue to be built with Maven.

Released artifacts can be found on Maven Central.

I don’t use Gradle and can’t provide you with technical support on how to use it, sorry.
